blank_issues_enabled: false
contact_links:
  - name: Feature Request ğŸ’¡
    url: https://github.com/Piyush240604/react-native-type-step-counter/discussions/new?category=ideas
    about: If you have a feature request, please create a new discussion on GitHub.
  - name: Discussions on GitHub ğŸ’¬
    url: https://github.com/Piyush240604/react-native-type-step-counter/discussions
    about: If this library works as promised but you need help, please ask questions there.
